---
title: "Reel Intelligence: MovieLens Clustering"
subtitle: "Final Project Report, Spring 2026"
author:
  - Ali Jabir
  - Isis Martínez
  - Susan Peck
date: "May 2, 2026"
format:
  pdf:
    pdf-engine: pdflatex
fontsize: 11pt
geometry: margin=1in
header-includes:
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{booktabs}
  - \usepackage{longtable}
  - \usepackage{array}
  - \usepackage{float}
  - \usepackage{setspace}
  - \usepackage{graphicx}
  - \usepackage{caption}
  - \usepackage{hyperref}
bibliography: refs.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 5.5,
  dpi = 120
)

library(dplyr)
library(ggplot2)
library(knitr)
library(scales)


source("compare_results_helpers.R")

compare_results <- build_compare_results_data(
  cache_root = file.path("..", "output", "benchmark_cache")
)

plot_df <- compare_results$plot_df
best_models_df <- compare_results$best_models_df
best_table <- compare_results$best_table
overall_best <- compare_results$overall_best
ari_df <- compare_results$ari_df
ari_summary <- compare_results$ari_summary
```


\begin{center}
\textbf{Clustering Analysis (Math 252)}\\
Professor: Dr. Cristina Tortora\\
Department of Computer Science\\
San Jose State University
\end{center}

# Abstract

TBD

[NOTE: ADD ANY OTHER INFORMATION NEEDED WITH CODE AND RESULTS LATER]

[ADD 3 DIFFERENT DATASETS]

```{r child="sections/01-introduction.Rmd"}
```

```{r child="sections/02-background.Rmd"}
```

```{r child="sections/03-dataset.Rmd"}
```

```{r child="sections/04-methods.Rmd"}
```

```{r child="sections/05-evaluation.Rmd"}
```

```{r child="sections/06-results.Rmd"}
```

```{r child="sections/07-conclusion.Rmd"}
```

```{r child="sections/08-appendix.Rmd"}
```

# References
